### ISSUE TITLE
how to deserialize?

### ISSUE THREAD

**Issue by victorhazbun87** [mohuk/ts-jsonapi#3]
there is no documentation about how to use this library, can you please help me?

**Comment by mohuk** [comment]
Hey

The API is the same as [jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer) since it is just a Typescript port.

A sample deserialize operation is just like
```typescript
let response: any = new Deserializer({
    keyForAttribute: 'camelCase'
}).deserialize(res.json());
```
