### ISSUE TITLE
keyForAttribute declaration appears to be incorrect

### ISSUE THREAD

**Issue by snortblt** [mohuk/ts-jsonapi#6]
The `Serializer.keyForAttribute` property type is declared as `(attribute: string) => string | caseOptions`. Providing a function that returns one of these caseOptions prevents correct serialization of any attributes. If the property is assigned to a `caseOptions` literal string instead serialization works. Should the type be declared as `((attribute: string) => string) | caseOptions` instead (note the parens)?

**Comment by mohuk** [comment]
Hey @snortblt 

Can you add a test case for it ? As in just to demonstrate your use case.

**Comment by christianengledercadt** [comment]
Please add the brackets, the are necessary for the ts compiler.

**Comment by christianengledercadt** [comment]
(attribute: string) => string | caseOption => ((attribute: string) => string) | caseOption

**Comment by mohuk** [comment]
Done 👍 

Thanks @snortblt and @christianengledercadt

**Comment by mohuk** [comment]
Released `v2.1.2` on npmjs.

https://www.npmjs.com/package/ts-jsonapi
